baseurl = "https://christophsteinke.com/"

languageCode = "de-de"
defaultContentLanguage = "de"
sectionPagesMenu = "main"

paginate = 5
paginatePath = "page"

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  baseFragment = "/"
  template = ""
  title = "Christoph Steinke"
  copyright = "Christoph Steinke"
  subtitle = "Künstler"

[taxonomies]
  paper = "papers"

[outputs]
  page = ["HTML", "JSON"]
  section = ["HTML", "JSON"]
  home = ["html", "JSON"]

[imaging]
  resampleFilter = "box"
  quality = 75
  anchor = "smart"

[languages]
  [languages.de]
    languageName = "deutsch"
    weight = 1
    
  [languages.en]
    languageName = "english"
    weight = 2
    subtitle = "Artist"
